"use client";
import { useEffect, useState, FC } from 'react';
import Image from 'next/image';
import { DEPARTMENT_LABELS, CATEGORY_LABELS } from '@/lib/constants';

interface Asset {
  _id: string;
  assetId?: string;
  name: string;
  department: string;
  category: string;
  status: string;
  acquired: string;
  date: string;
  site: string;
  quantity?: number;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  loggedBy?: {
    name: string;
    email: string;
  };
  // Category-specific fields
  [key: string]: unknown;
}

interface AssetTableProps {
  refreshTrigger?: number;
  onEditAsset?: (asset: Asset) => void;
}

const AssetTable: FC<AssetTableProps> = ({ refreshTrigger, onEditAsset }) => {
  const [assets, setAssets] = useState<Asset[]>([]);
  const [search, setSearch] = useState('');
  const [filtered, setFiltered] = useState<Asset[]>([]);
  const [loading, setLoading] = useState(true);
  const [departmentFilter, setDepartmentFilter] = useState('all');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [locationFilter, setLocationFilter] = useState('all');

  const exportToCSV = () => {
    if (filtered.length === 0) return;

    const headers = [
      'Asset ID',
      'Asset Name',
      'Department',
      'Category',
      'Status',
      'Acquired',
      'Date Acquired',
      'Wildlife Centre',
      'Quantity',
      'Logged By',
      'Created Date',
      'Last Updated'
    ];

    const csvData = filtered.map(asset => [
      `"${asset.assetId || 'N/A'}"`,
      `"${asset.name}"`,
      `"${DEPARTMENT_LABELS[asset.department] || asset.department}"`,
      `"${CATEGORY_LABELS[asset.category] || asset.category}"`,
      `"${asset.status}"`,
      `"${asset.acquired}"`,
      `"${new Date(asset.date).toLocaleDateString('en-IN')}"`,
      `"${asset.site}"`,
      `"${asset.quantity || 1}"`,
      `"${asset.loggedBy?.name || 'Unknown'}"`,
      `"${asset.createdAt ? new Date(asset.createdAt).toLocaleDateString('en-IN') : 'N/A'}"`,
      `"${asset.updatedAt ? new Date(asset.updatedAt).toLocaleDateString('en-IN') : 'N/A'}"`
    ]);

    const totalAssets = filtered.length;
    const activeAssets = filtered.filter(a => a.status === 'active').length;
    const donatedAssets = filtered.filter(a => a.acquired === 'donated').length;
    const boughtAssets = filtered.filter(a => a.acquired === 'bought').length;
    const uniqueLocations = new Set(filtered.map(a => a.site)).size;

    const summaryRows = [
      [''],
      ['"=== WILDLIFE SOS INVENTORY SUMMARY ==="'],
      [`"Total Assets:"`, `"${totalAssets}"`],
      [`"Active Assets:"`, `"${activeAssets}"`],
      [`"Donated Items:"`, `"${donatedAssets}"`],
      [`"Purchased Items:"`, `"${boughtAssets}"`],
      [`"Wildlife Centres Covered:"`, `"${uniqueLocations}"`],
      [''],
      [`"Export Date:"`, `"${new Date().toLocaleDateString('en-IN')} ${new Date().toLocaleTimeString('en-IN')}"`],
      [`"Generated by:"`, `"Wildlife SOS Inventory360 System"`]
    ];

    const csvContent = [
      headers.join(','),
      ...csvData.map(row => row.join(',')),
      ...summaryRows.map(row => row.join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    const dateStr = new Date().toISOString().split('T')[0];
    let filename = `wildlife-sos-assets-${dateStr}`;
    if (departmentFilter !== 'all') filename += `-${departmentFilter}`;
    if (locationFilter !== 'all') filename += `-${locationFilter.replace(/\s+/g, '-')}`;

    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  useEffect(() => {
    async function fetchAssets() {
      setLoading(true);
      try {
        const res = await fetch('/api/asset');
        const data = await res.json();
        setAssets(data.assets || []);
      } catch (error) {
        console.error('Failed to fetch assets:', error);
      }
      setLoading(false);
    }
    fetchAssets();
  }, [refreshTrigger]);

  useEffect(() => {
    let result = assets.filter(a =>
      a.name.toLowerCase().includes(search.toLowerCase()) ||
      a.site.toLowerCase().includes(search.toLowerCase()) ||
      (a.assetId || '').toLowerCase().includes(search.toLowerCase()) ||
      (a.department || '').toLowerCase().includes(search.toLowerCase()) ||
      (a.category || '').toLowerCase().includes(search.toLowerCase())
    );

    if (departmentFilter !== 'all') {
      result = result.filter(a => a.department === departmentFilter);
    }

    if (categoryFilter !== 'all') {
      result = result.filter(a => a.category === categoryFilter);
    }

    if (locationFilter !== 'all') {
      result = result.filter(a => a.site === locationFilter);
    }

    setFiltered(result);
  }, [search, assets, departmentFilter, categoryFilter, locationFilter]);

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'medicine': return 'text-red-700 bg-red-50';
      case 'medical-supplies': return 'text-orange-700 bg-orange-50';
      case 'medical-equipment': return 'text-blue-700 bg-blue-50';
      case 'vehicle': return 'text-purple-700 bg-purple-50';
      case 'av-equipment': return 'text-indigo-700 bg-indigo-50';
      case 'furniture': return 'text-amber-700 bg-amber-50';
      case 'machinery': return 'text-slate-700 bg-slate-100';
      default: return 'text-gray-700 bg-gray-50';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'text-green-700 bg-green-50';
      case 'phased out': return 'text-red-700 bg-red-50';
      default: return 'text-gray-700 bg-gray-50';
    }
  };

  // Get unique categories from current assets (filtered by department if set)
  const availableCategories = Array.from(
    new Set(
      assets
        .filter(a => departmentFilter === 'all' || a.department === departmentFilter)
        .map(a => a.category)
    )
  ).sort();

  if (loading) {
    return (
      <div className="text-center py-12 font-wildlife">
        <div className="text-6xl mb-4">🐻</div>
        <div className="text-wildlife-green-text font-semibold text-lg">Loading conservation assets...</div>
        <div className="text-wildlife-brown-dark text-sm mt-2">Fetching inventory from rescue centres</div>
      </div>
    );
  }

  return (
    <div className="font-wildlife">
      {/* Search and Filter Controls */}
      <div className="mb-6 space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center space-y-4 lg:space-y-0 lg:space-x-4">
          {/* Search */}
          <div className="flex-1">
            <div className="relative">
              <span className="absolute left-3 top-1/2 transform -translate-y-1/2 text-wildlife-brown">🔍</span>
              <input
                className="input pl-10"
                placeholder="Search by name, asset ID, site, department..."
                value={search}
                onChange={e => setSearch(e.target.value)}
              />
            </div>
          </div>

          {/* Filters */}
          <div className="flex flex-col md:flex-row md:space-x-3 space-y-3 md:space-y-0">
            <select
              className="input md:w-48"
              value={departmentFilter}
              onChange={e => {
                setDepartmentFilter(e.target.value);
                setCategoryFilter('all');
              }}
            >
              <option value="all">All Departments</option>
              {Array.from(new Set(assets.map(a => a.department))).sort().map(d => (
                <option key={d} value={d}>{DEPARTMENT_LABELS[d] || d}</option>
              ))}
            </select>

            <select
              className="input md:w-48"
              value={categoryFilter}
              onChange={e => setCategoryFilter(e.target.value)}
            >
              <option value="all">All Categories</option>
              {availableCategories.map(c => (
                <option key={c} value={c}>{CATEGORY_LABELS[c] || c}</option>
              ))}
            </select>

            <select
              className="input md:w-56"
              value={locationFilter}
              onChange={e => setLocationFilter(e.target.value)}
            >
              <option value="all">All Centres</option>
              {Array.from(new Set(assets.map(a => a.site))).sort().map(site => (
                <option key={site} value={site}>{site}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Results Summary */}
        <div className="flex items-center justify-between text-sm text-wildlife-brown-dark">
          <span>
            Showing {filtered.length} of {assets.length} assets
            {departmentFilter !== 'all' && ` · ${DEPARTMENT_LABELS[departmentFilter]}`}
            {categoryFilter !== 'all' && ` · ${CATEGORY_LABELS[categoryFilter]}`}
            {locationFilter !== 'all' && ` · ${locationFilter}`}
          </span>
          <div className="flex items-center space-x-3">
            <button
              onClick={exportToCSV}
              disabled={filtered.length === 0}
              className={`flex items-center space-x-2 px-4 py-2 rounded-xl text-sm font-medium transition-colors duration-200 ${
                filtered.length > 0
                  ? 'bg-wildlife-green text-white hover:bg-wildlife-green-dark'
                  : 'bg-gray-300 text-gray-500 cursor-not-allowed'
              }`}
            >
              <span>Export CSV ({filtered.length})</span>
            </button>

            {(search || departmentFilter !== 'all' || categoryFilter !== 'all' || locationFilter !== 'all') && (
              <button
                onClick={() => {
                  setSearch('');
                  setDepartmentFilter('all');
                  setCategoryFilter('all');
                  setLocationFilter('all');
                }}
                className="text-wildlife-green-text hover:underline text-sm"
              >
                Clear filters
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Assets Table */}
      <div className="overflow-x-auto">
        <table className="min-w-full bg-white rounded-2xl shadow-wildlife overflow-hidden border border-wildlife-green/20">
          <thead className="bg-wildlife-green text-white">
            <tr>
              <th className="px-4 py-4 text-left font-semibold text-sm">Asset ID</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Name</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Department</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Category</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Status</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Qty</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Date</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Centre</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Logged By</th>
              <th className="px-4 py-4 text-left font-semibold text-sm">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((asset, index) => (
              <tr
                key={asset._id}
                className={`border-b border-wildlife-green/10 hover:bg-wildlife-green/5 transition-colors ${
                  index % 2 === 0 ? 'bg-white' : 'bg-wildlife-ivory/30'
                }`}
              >
                <td className="px-4 py-3">
                  <span className="font-mono text-sm font-bold text-wildlife-green-text">
                    {asset.assetId || '—'}
                  </span>
                </td>
                <td className="px-4 py-3">
                  <div className="font-medium text-wildlife-black">{asset.name}</div>
                </td>
                <td className="px-4 py-3 text-sm text-wildlife-brown-dark">
                  {DEPARTMENT_LABELS[asset.department] || asset.department}
                </td>
                <td className="px-4 py-3">
                  <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getCategoryColor(asset.category)}`}>
                    {CATEGORY_LABELS[asset.category] || asset.category}
                  </span>
                </td>
                <td className="px-4 py-3">
                  <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(asset.status)}`}>
                    {asset.status}
                  </span>
                </td>
                <td className="px-4 py-3 text-sm text-wildlife-brown-dark">
                  {asset.quantity || 1}
                </td>
                <td className="px-4 py-3 text-sm text-wildlife-brown-dark">
                  {new Date(asset.date).toLocaleDateString('en-IN')}
                </td>
                <td className="px-4 py-3">
                  <div className="text-sm font-medium text-wildlife-black">{asset.site}</div>
                </td>
                <td className="px-4 py-3">
                  <div className="text-sm">
                    <div className="font-medium text-wildlife-black">
                      {asset.loggedBy?.name || 'Unknown'}
                    </div>
                    {asset.loggedBy?.email && (
                      <div className="text-xs text-wildlife-brown-dark">
                        {asset.loggedBy.email}
                      </div>
                    )}
                  </div>
                </td>
                <td className="px-4 py-3">
                  <button
                    onClick={() => onEditAsset?.(asset)}
                    className="inline-flex items-center space-x-1 px-3 py-1 bg-wildlife-green/10 hover:bg-wildlife-green/20 text-wildlife-green-text rounded-lg text-sm font-medium transition-colors duration-200"
                  >
                    <span>Edit</span>
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Empty State */}
        {filtered.length === 0 && !loading && (
          <div className="text-center py-12 bg-white rounded-2xl shadow-wildlife border border-wildlife-green/20 mt-4">
            <div className="w-16 h-16 mx-auto mb-4 relative">
              <Image
                src="/download (2).jpg"
                alt="Wildlife SOS Logo"
                fill
                className="object-contain rounded-full"
              />
            </div>
            <h3 className="text-xl font-semibold text-wildlife-black mb-2">
              No assets found
            </h3>
            <p className="text-wildlife-brown-dark mb-4">
              {search || departmentFilter !== 'all' || categoryFilter !== 'all' || locationFilter !== 'all'
                ? 'No assets match your current filters. Try adjusting your search.'
                : 'Start by adding your first asset to the inventory.'
              }
            </p>
            {(search || departmentFilter !== 'all' || categoryFilter !== 'all' || locationFilter !== 'all') && (
              <button
                onClick={() => {
                  setSearch('');
                  setDepartmentFilter('all');
                  setCategoryFilter('all');
                  setLocationFilter('all');
                }}
                className="btn-wildlife"
              >
                Clear filters
              </button>
            )}
          </div>
        )}
      </div>

      {/* Stats */}
      {assets.length > 0 && (
        <div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-white rounded-xl p-4 shadow-wildlife border border-wildlife-green/20 text-center">
            <div className="text-2xl text-wildlife-green-text font-bold">
              {assets.filter(a => a.status === 'active').length}
            </div>
            <div className="text-sm text-wildlife-brown-dark">Active Assets</div>
          </div>
          <div className="bg-white rounded-xl p-4 shadow-wildlife border border-wildlife-green/20 text-center">
            <div className="text-2xl text-wildlife-green-text font-bold">
              {new Set(assets.map(a => a.department)).size}
            </div>
            <div className="text-sm text-wildlife-brown-dark">Departments</div>
          </div>
          <div className="bg-white rounded-xl p-4 shadow-wildlife border border-wildlife-green/20 text-center">
            <div className="text-2xl text-wildlife-green-text font-bold">
              {assets.filter(a => a.acquired === 'donated').length}
            </div>
            <div className="text-sm text-wildlife-brown-dark">Donated Items</div>
          </div>
          <div className="bg-white rounded-xl p-4 shadow-wildlife border border-wildlife-green/20 text-center">
            <div className="text-2xl text-wildlife-green-text font-bold">
              {new Set(assets.map(a => a.site)).size}
            </div>
            <div className="text-sm text-wildlife-brown-dark">Centres</div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AssetTable;
